---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs401-proj2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cs401-proj2
  template:
    metadata:
      labels:
        app: cs401-proj2
    spec:
      containers:
        - name: cs401-proj2
          image: quay.io/haydencaffrey/cs401_proj2:v0.4
          ports:
            - containerPort: 5014
