apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs401-proj2-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: cs401-proj2
          image: quay.io/haydencaffrey/cs401_proj2
          ports:
            - containerPort: 5014


